FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY phenology/ .

EXPOSE 8002

CMD ["gunicorn", "phenology.wsgi:application", "--bind", "0.0.0.0:8002", "--workers", "3"]