# Generated by Django 5.2.12 on 2026-04-03 17:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the farm', max_length=255)),
                ('organic_certified', models.BooleanField(default=False, help_text='Whether farm is organically certified')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variety', models.CharField(help_text='Grape variety planted in this block', max_length=255)),
                ('name', models.CharField(help_text='Block name/identifier', max_length=255)),
                ('other_language_name', models.CharField(blank=True, help_text='Alternative name in local language', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flight_date', models.DateField(help_text='Date of the flight')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flights', to='api.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flights_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-flight_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path_id', models.CharField(help_text='S3 path or file identifier', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_created', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.flight')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Time period (e.g., "2024-Q1", "2024-01")', max_length=50)),
                ('fungicide_reduction', models.DecimalField(blank=True, decimal_places=2, help_text='Fungicide reduction percentage', max_digits=10, null=True)),
                ('fuel_reduction', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel reduction percentage', max_digits=10, null=True)),
                ('co2_reduction', models.DecimalField(blank=True, decimal_places=2, help_text='CO2 reduction in kg', max_digits=10, null=True)),
                ('yield_reduction', models.DecimalField(blank=True, decimal_places=2, help_text='Yield reduction percentage (negative = increase)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='api.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpis_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, help_text='Latitude coordinate', max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, help_text='Longitude coordinate', max_digits=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.block')),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.farm')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhenologyStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_name', models.CharField(help_text='Growth stage name (e.g., Bud Break, Flowering, Veraison)', max_length=100)),
                ('start_date', models.DateField(help_text='Start date of this stage')),
                ('end_date', models.DateField(blank=True, help_text='End date of this stage', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this stage', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phenology_stages', to='api.block')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction_details', models.JSONField(default=dict, help_text='Detailed prediction data as JSON')),
                ('result', models.CharField(blank=True, help_text='Prediction result summary', max_length=255, null=True)),
                ('suggestion', models.TextField(blank=True, help_text='AI-generated suggestions', null=True)),
                ('stress_parameters', models.JSONField(default=dict, help_text='Stress level parameters (water, nutrient, disease, etc.)')),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, help_text='Model confidence score (0-100)', max_digits=5, null=True)),
                ('yield_prediction', models.DecimalField(blank=True, decimal_places=2, help_text='Predicted yield (tons/hectare)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.block')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_created', to=settings.AUTH_USER_MODEL)),
                ('phenology_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.phenologystage')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(help_text='Time period (e.g., "2024-Q1", "2024-01")', max_length=50)),
                ('action_type', models.CharField(choices=[('SPRAY', 'Spray Application'), ('IRRIGATE', 'Irrigation'), ('HARVEST', 'Harvest'), ('PRUNE', 'Pruning'), ('FERTILIZE', 'Fertilization'), ('SCOUT', 'Scouting'), ('OTHER', 'Other')], help_text='Type of action performed', max_length=20)),
                ('chemical_type', models.CharField(choices=[('FUNGICIDE', 'Fungicide'), ('INSECTICIDE', 'Insecticide'), ('HERBICIDE', 'Herbicide'), ('FERTILIZER', 'Fertilizer'), ('OTHER', 'Other'), ('NONE', 'None')], default='NONE', help_text='Type of chemical used', max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text='Quantity applied (liters/kg)', max_digits=10, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost of action in local currency', max_digits=12, null=True)),
                ('yield_impact', models.DecimalField(blank=True, decimal_places=2, help_text='Impact on yield (percentage)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_updated', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.block')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['block', 'period'], name='api_action_block_i_e204ed_idx'), models.Index(fields=['action_type'], name='api_action_action__a4cde6_idx'), models.Index(fields=['period'], name='api_action_period_9563b0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['name'], name='api_farm_name_ecf83e_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['organic_certified'], name='api_farm_organic_4e9c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['farm'], name='api_block_farm_id_936064_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['variety'], name='api_block_variety_29486c_idx'),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['name'], name='api_block_name_9bfbe2_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['block', 'flight_date'], name='api_flight_block_i_77459f_idx'),
        ),
        migrations.AddIndex(
            model_name='flight',
            index=models.Index(fields=['flight_date'], name='api_flight_flight__b44784_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['flight'], name='api_image_flight__93f2ab_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['block'], name='api_image_block_i_1805c1_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['block', 'period'], name='api_kpi_block_i_5bf7dc_idx'),
        ),
        migrations.AddIndex(
            model_name='kpi',
            index=models.Index(fields=['period'], name='api_kpi_period_735268_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kpi',
            unique_together={('block', 'period')},
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['farm'], name='api_locatio_farm_id_6e751b_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['block'], name='api_locatio_block_i_84de03_idx'),
        ),
        migrations.AddIndex(
            model_name='phenologystage',
            index=models.Index(fields=['block', 'start_date'], name='api_phenolo_block_i_fc7ab5_idx'),
        ),
        migrations.AddIndex(
            model_name='phenologystage',
            index=models.Index(fields=['stage_name'], name='api_phenolo_stage_n_ed0c4f_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['block'], name='api_predict_block_i_073bb7_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['phenology_stage'], name='api_predict_phenolo_f32a12_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['created_at'], name='api_predict_created_a16c78_idx'),
        ),
    ]
